<%
'This file contains the constants for this site's lastest additions (cust #10312

Const IncludeAdditionsMembers = 1
Const IncludeAdditionsInfoPages = 1
Const IncludeAdditionsAnnouncements = 1
Const IncludeAdditionsMeetings = 1
Const IncludeAdditionsStories = 1
Const IncludeAdditionsCalendar = 1
Const IncludeAdditionsLinks = 1
Const IncludeAdditionsQuotes = 1
Const IncludeAdditionsForumMessages = 1
Const IncludeAdditionsVotingPolls = 1
Const IncludeAdditionsQuizzes = 1
Const IncludeAdditionsGuestbook = 1
Const IncludeAdditionsMedia = 1
Const IncludeAdditionsPhotos = 1
Const IncludeAdditionsPhotoCaptions = 1
Const IncludeAdditionsReviews = 1

Const IncludeAdditionsMembersAuthor = 1
Const IncludeAdditionsInfoPagesAuthor = 1
Const IncludeAdditionsAnnouncementsAuthor = 1
Const IncludeAdditionsMeetingsAuthor = 1
Const IncludeAdditionsStoriesAuthor = 1
Const IncludeAdditionsCalendarAuthor = 1
Const IncludeAdditionsLinksAuthor = 1
Const IncludeAdditionsQuotesAuthor = 1
Const IncludeAdditionsForumMessagesAuthor = 1
Const IncludeAdditionsVotingPollsAuthor = 1
Const IncludeAdditionsQuizzesAuthor = 1
Const IncludeAdditionsGuestbookAuthor = 1
Const IncludeAdditionsMediaAuthor = 1
Const IncludeAdditionsPhotosAuthor = 1
Const IncludeAdditionsPhotoCaptionsAuthor = 1
Const IncludeAdditionsReviewsAuthor = 1
'End Constants
%>
