<%

Const IncludeStatsPopularMembers = 1
Const IncludeStatsPopularInfoPages = 1
Const IncludeStatsPopularAnnouncements = 1
Const IncludeStatsPopularMeetings = 1
Const IncludeStatsPopularStories = 1
Const IncludeStatsPopularCalendar = 1
Const IncludeStatsPopularLinks = 1
Const IncludeStatsPopularQuotes = 1
Const IncludeStatsPopularForumMessages = 1
Const IncludeStatsPopularVotingPolls = 1
Const IncludeStatsPopularQuizzes = 1
Const IncludeStatsPopularGuestbook = 1
Const IncludeStatsPopularMedia = 1
Const IncludeStatsPopularPhotos = 1
Const IncludeStatsPopularPhotoCaptions = 1
Const IncludeStatsPopularReviews = 1

Const IncludeStatsRatedMembers = 1
Const IncludeStatsRatedInfoPages = 1
Const IncludeStatsRatedAnnouncements = 1
Const IncludeStatsRatedMeetings = 1
Const IncludeStatsRatedStories = 1
Const IncludeStatsRatedCalendar = 1
Const IncludeStatsRatedLinks = 1
Const IncludeStatsRatedQuotes = 1
Const IncludeStatsRatedForumMessages = 1
Const IncludeStatsRatedVotingPolls = 1
Const IncludeStatsRatedQuizzes = 1
Const IncludeStatsRatedGuestbook = 1
Const IncludeStatsRatedMedia = 1
Const IncludeStatsRatedPhotos = 1
Const IncludeStatsRatedPhotoCaptions = 1
Const IncludeStatsRatedReviews = 1

Const IncludeStatsSummaryHomePage = 1
Const IncludeStatsSummaryMembers = 1
Const IncludeStatsSummaryInfoPages = 1
Const IncludeStatsSummaryAnnouncements = 1
Const IncludeStatsSummaryMeetings = 1
Const IncludeStatsSummaryStories = 1
Const IncludeStatsSummaryCalendar = 1
Const IncludeStatsSummaryLinks = 1
Const IncludeStatsSummaryQuotes = 1
Const IncludeStatsSummaryForumMessages = 1
Const IncludeStatsSummaryVotingPolls = 1
Const IncludeStatsSummaryQuizzes = 1
Const IncludeStatsSummaryGuestbook = 1
Const IncludeStatsSummaryMedia = 1
Const IncludeStatsSummaryPhotos = 1
Const IncludeStatsSummaryPhotoCaptions = 1
Const IncludeStatsSummaryReviews = 1
'End Constants
%>
